<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-1J0QRU3" ignored="0" name="测试模块一" tests="4" failures="2" timestamp="29 十一月 2018 01:21:29 GMT" time="0.089" errors="0">
  <testcase name="test1" time="0.024" classname="org.extentreport.TestMethodDemo">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at org.extentreport.TestMethodDemo.test1(TestMethodDemo.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="org.extentreport.TestMethodDemo"/>
  <testcase name="test3" time="0.011" classname="org.extentreport.TestMethodDemo"/>
  <testcase name="logDemo" time="0.001" classname="org.extentreport.TestMethodDemo">
    <failure type="java.lang.RuntimeException" message="手动抛出de异常">
      <![CDATA[java.lang.RuntimeException: 手动抛出de异常
at org.extentreport.TestMethodDemo.logDemo(TestMethodDemo.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- logDemo -->
</testsuite> <!-- 测试模块一 -->
